name: CD

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: notely-464907
  GCP_REGION: us-central1
  AR_REPO: notely-ar-repo
  IMAGE_NAME: notely

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Build production binary
        run: scripts/buildprod.sh

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          TAG="latest-${GITHUB_SHA:0:8}"
          gcloud builds submit \
            --tag ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${AR_REPO}/${IMAGE_NAME}:${TAG} \
            .

      - name: Verify pushed images
        run: |
          gcloud artifacts docker images list \
            ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${AR_REPO}

      - name: Deploy to Cloud Run
        run: |
          TAG="latest-${GITHUB_SHA:0:8}"
          gcloud run deploy notely \
            --image ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${AR_REPO}/${IMAGE_NAME}:${TAG} \
            --region ${GCP_REGION} \
            --allow-unauthenticated \
            --project ${GCP_PROJECT} \
            --max-instances=4
